from fpdf import FPDF
from datetime import datetime
import os

class ReportGenerator:
    def __init__(self, database_manager):
        self.db = database_manager
    
    # Format angka menjadi format currency Indonesia
    def format_currency(self, value):
        return f"Rp{value:,.0f}".replace(",", ".")
    
    # Generate PDF report dari data history
    def generate_pdf_report(self):
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 10, "LAPORAN PERHITUNGAN CICILAN RUMAH", 0, 1, "C")
        pdf.ln(5)
        
        pdf.set_font("Arial", "", 12)
        pdf.cell(0, 10, f"Tanggal Generate: {datetime.now().strftime('%d-%m-%Y %H:%M')}", 0, 1)
        pdf.ln(10)
        
        # Ambil data
        history_data = self.db.ambil_history()
        
        if not history_data:
            pdf.cell(0, 10, "Tidak ada data history", 0, 1)
            return
        
        # Summary
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "RINGKASAN:", 0, 1)
        
        total_proyek = len(history_data)
        total_keuntungan = sum(row[7] for row in history_data)
        total_nilai_proyek = sum(row[4] for row in history_data)
        rata_keuntungan = total_keuntungan / total_proyek if total_proyek > 0 else 0
        
        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 8, f"Total Proyek: {total_proyek}", 0, 1)
        pdf.cell(0, 8, f"Total Nilai Proyek: {self.format_currency(total_nilai_proyek)}", 0, 1)
        pdf.cell(0, 8, f"Total Keuntungan: {self.format_currency(total_keuntungan)}", 0, 1)
        pdf.cell(0, 8, f"Rata-rata Keuntungan: {self.format_currency(rata_keuntungan)}", 0, 1)
        pdf.ln(10)
        
        # Tabel data
        pdf.set_font("Arial", "B", 10)
        headers = ["No", "Proyek", "Harga Asal", "Harga Jual", "Lama", "Cicilan/Thn", "Keuntungan"]
        
        col_widths = [15, 40, 35, 35, 20, 35, 35]
        
        # Header tabel
        for i, header in enumerate(headers):
            pdf.cell(col_widths[i], 10, header, 1, 0, "C")
        pdf.ln()
        
        # Isi tabel
        pdf.set_font("Arial", "", 8)
        for idx, row in enumerate(history_data, 1):
            # Format data
            proyek = row[2][:20] + "..." if len(row[2]) > 20 else row[2]
            harga_asal = self.format_currency(row[3])
            harga_jual = self.format_currency(row[4])
            cicilan = f"{row[5]}th"
            cicilan_tahun = self.format_currency(row[6])
            keuntungan = self.format_currency(row[7])
            
            data = [str(idx), proyek, harga_asal, harga_jual, cicilan, cicilan_tahun, keuntungan]
            
            for i, item in enumerate(data):
                pdf.cell(col_widths[i], 10, item, 1, 0, "C")
            pdf.ln()
        
        # Footer
        pdf.ln(15)
        pdf.set_font("Arial", "I", 8)
        pdf.cell(0, 10, f"Generated by Super Calculator Cicilan Rumah - {datetime.now().strftime('%d/%m/%Y %H:%M')}", 0, 1)
        
        # Simpan file
        os.makedirs("history", exist_ok=True)
        filename = f"history/laporan_cicilan_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        pdf.output(filename)
        
        return filename